import { CarCardProps } from "@/lib/definitions";

const cars: CarCardProps[] = [
  {
    id: "1",
    name: "Koenigsegg",
    type: "Sport",
    img: "/01.png",
    fuel: "90L",
    steering: "Manual",
    capacity: "2Person",
    price: "99.00",
    discount: "",
    isLike: false,
    recent: true,
    recommend: false,
  },
  {
    id: "2",
    name: "Nissan GT - R",
    type: "Sport",
    img: "/02.png",
    fuel: "80L",
    steering: "Manual",
    capacity: "2Person",
    price: "80.00",
    discount: "100.00",
    isLike: false,
    recent: true,
    recommend: false,
  },
  {
    id: "3",
    name: "Rolls - Royce",
    type: "Sedan",
    img: "/03.png",
    fuel: "70L",
    steering: "Manual",
    capacity: "4Person",
    price: "96.00",
    discount: "",
    isLike: true,
    recent: true,
    recommend: false,
  },
  {
    id: "5",
    name: "All New Rush",
    type: "SUV",
    img: "/05.png",
    fuel: "70L",
    steering: "Manual",
    capacity: "6Person",
    price: "72.00",
    discount: "80.00",
    isLike: false,
    recent: false,
    recommend: true,
  },
  {
    id: "6",
    name: "CR  - V",
    type: "SUV",
    img: "/06.png",
    fuel: "80L",
    steering: "Manual",
    capacity: "6Person",
    price: "80.00",
    discount: "",
    isLike: false,
    recent: false,
    recommend: false,
  },
  {
    id: "7",
    name: "All New Terios",
    type: "SUV",
    img: "/07.png",
    fuel: "90L",
    steering: "Manual",
    capacity: "6Person",
    price: "74.00",
    discount: "",
    isLike: false,
    recent: false,
    recommend: true,
  },
  {
    id: "8",
    name: "CR  - V",
    type: "SUV",
    img: "/08.png",
    fuel: "80L",
    steering: "Manual",
    capacity: "6Person",
    price: "80.00",
    discount: "",
    isLike: true,
    recommend: true,
    recent: false,
  },
  {
    id: "10",
    name: "New MG ZS",
    type: "SUV",
    img: "/10.png",
    fuel: "80L",
    steering: "Manual",
    capacity: "6Person",
    price: "80.00",
    discount: "",
    isLike: false,
    recent: true,
    recommend: false,
  },
  {
    id: "11",
    name: "MG ZX Excite",
    type: "Hatchback",
    img: "/11.png",
    fuel: "90L",
    steering: "Manual",
    capacity: "4Person",
    price: "74.00",
    discount: "",
    isLike: true,
    recent: false,
    recommend: true,
  },
  {
    id: "12",
    name: "New MG ZS",
    type: "SUV",
    img: "/12.png",
    fuel: "80L",
    steering: "Manual",
    capacity: "6Person",
    price: "80.00",
    discount: "",
    isLike: false,
    recent: false,
    recommend: true,
  },
];

export default cars;
