import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { Toaster } from "react-hot-toast";
import AppProvider from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-main flex justify-center w-full">
      <body className="mx-auto max-w-screen-xl w-full bg-main transition-colors duration-200">
        <AppProvider>
          <Header />
          <Toaster />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
